# Generated by Django 5.0.2 on 2024-03-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderproduct',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название'),
        ),
    ]
